new.py:129: RuntimeWarning: invalid value encountered in greater
  a = (data1[i][2] > thres_distance)*1
new.py:260: RuntimeWarning: invalid value encountered in greater
  a = (data1_t[i][2] > thres_distance)*1
Traceback (most recent call last):
  File "new.py", line 616, in <module>
    svd = tf.matmul(ud, tf.transpose(conv2_svd[:,0,:,:],(0,2,1))) 
NameError: name 'conv2_svd' is not defined
