new.py:129: RuntimeWarning: invalid value encountered in greater
  a = (data1[i][2] > thres_distance)*1
